name: otp
version: 2.2.3
description: RFC6238 Time-Based One-Time Password / Google Authenticator Library
homepage: https://github.com/Daegalus/dart-otp
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  base32: ">=1.1.1 <2.0.0"
  crypto: ">=2.1.3 <3.0.0"
  convert: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: any
  pedantic: ^1.0.0
